# Generated by Django 4.1.3 on 2022-11-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_company')),
                ('name', models.CharField(max_length=30, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('city', models.CharField(max_length=30, verbose_name='cidade')),
                ('address', models.CharField(max_length=60, verbose_name='endereço')),
                ('market_category', models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia')], max_length=3, verbose_name='nicho_de_mercado')),
                ('company_characteristics', models.TextField(verbose_name='caracteristicas_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=30, verbose_name='tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='titulo')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('lvl_experience', models.CharField(choices=[('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior')], max_length=2, verbose_name='nivel_experiencia')),
                ('final_date', models.DateField(verbose_name='data final')),
                ('status', models.CharField(choices=[('I', 'Interesse'), ('C', 'Currículo enviado'), ('E', 'Entrevista'), ('D', 'Desafio técnico'), ('F', 'Finalizado')], max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companys.company', verbose_name='empresa')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='technology',
            field=models.ManyToManyField(to='companys.technology', verbose_name='tecnologias'),
        ),
    ]
