# Generated by Django 4.1.3 on 2022-11-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='technologies_matereds',
            field=models.ManyToManyField(to='companys.technology'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='technologies_to_study',
            field=models.ManyToManyField(related_name='estudar', to='companys.technology'),
        ),
    ]
