# Generated by Django 4.1.3 on 2022-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_vacancy_technologies_matereds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='found_ind',
            field=models.CharField(default=2, max_length=30, verbose_name='encontrada em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='lvl_experience',
            field=models.CharField(choices=[('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior')], max_length=2, verbose_name='nivel experiencia'),
        ),
    ]
