# Generated by Django 4.1.3 on 2022-11-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_rename_technology_study_jobs_technology_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
