# Generated by Django 4.1.3 on 2022-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_vacancy_found_ind_alter_vacancy_lvl_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='found_ind',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='lvl_experience',
            field=models.CharField(choices=[('J', 'Júnior'), ('P', 'Pleno'), ('S', 'Sênior')], max_length=2, verbose_name='nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='technologies_matereds',
            field=models.ManyToManyField(to='companys.technology', verbose_name='Tecnologias dominadas'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='technologies_to_study',
            field=models.ManyToManyField(related_name='estudar', to='companys.technology', verbose_name='Tecnologias para estudar'),
        ),
    ]
