# Generated by Django 4.1.3 on 2022-11-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0006_remove_jobs_technologies_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_category',
            field=models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia')], max_length=3, verbose_name='nicho_de_mercado'),
        ),
    ]
