# Generated by Django 4.1.3 on 2022-11-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0002_vacancy_technologies_matereds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('B', 'Baixa'), ('A', 'Alta'), ('U', 'Urgente')], max_length=1)),
                ('date', models.DateField()),
                ('concluded', models.BooleanField(default=False)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.vacancy')),
            ],
        ),
    ]
