# Generated by Django 4.1.3 on 2022-11-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_vacancy_technologies_matereds_and_more'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('main_text', models.TextField()),
                ('sent', models.BooleanField()),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companys.vacancy')),
            ],
        ),
    ]
